//
// Created by hugo on 10/11/22.
//

#ifndef BATTERY_ESTIMATOR_ADVANCEDBATTERYESTIMATION_H
#define BATTERY_ESTIMATOR_ADVANCEDBATTERYESTIMATION_H


class AdvancedBatteryEstimation {

};


#endif //BATTERY_ESTIMATOR_ADVANCEDBATTERYESTIMATION_H
